### ISSUE TITLE
Add instructions on how to set up this project in the README.md file

### ISSUE THREAD

**Issue by coyksdev** [gbesmano/TravelmateW#2]

**Comment by gbesmano** [comment]
done

**Comment by coyksdev** [comment]
i'm setting up the project now. here’s the guide for markdown as well, so you can format the readme properly: https://www.markdownguide.org/cheat-sheet/

**Comment by coyksdev** [comment]
@gbesmano, can you provide login credentials? Users passwords are encrypted in MongoDB.

**Comment by gbesmano** [comment]
You can use :

Admin:
vpasco@gmail.com
12345

bins@gmail.com
12345

**Comment by coyksdev** [comment]
@gbesmano do i need to start the vite app?

**Comment by gbesmano** [comment]
You can run mongodb compass and click on the connection you have made to load. Then on your visual studio code you can open the folder of the  source code then from there open a terminal and type php artisan serve and there should be no issues from then on.

**Comment by coyksdev** [comment]
i mean the Vite, i can see that you created a react app using Vite. Do I still need to run it?

**Comment by gbesmano** [comment]
No, you don't need to run it

**Comment by coyksdev** [comment]
@gbesmano, do you have any idea why it is showing these errors?

https://github.com/user-attachments/assets/cd83cdc5-4473-42d0-bcd2-02ca369f70d1

**Comment by gbesmano** [comment]
i dont have any problem accessing it 
![Capture](https://github.com/user-attachments/assets/d3c40084-8881-4b83-ba2e-a30455261018)


Can you try this instead?


in your .env copy and paste this:


APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:RBv7W2W4Z27ZNok5vdcx5ppAENQ2nb2A6MWROzf2yU8=
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=http://localhost

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mongodb
DB_HOST=127.0.0.1
DB_PORT=27017
DB_DATABASE=project11
DB_USERNAME=
DB_PASSWORD=
DB_URI=mongodb+srv://gbesmano:123@cluster0.fkz2r.mongodb.net/

SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

**Comment by coyksdev** [comment]
Thanks, it worked
